### PR TITLE
Refactor ufuncs module into lib module

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
@caspervdw I started this afternoon to try to split the files a bit more and have a separate ufuncs file and a general `lib` module instead of `ufuncs` (since not everything are ufuncs, I think mentioned it before on some PR, not sure if you are OK with that?).

Then I saw that you also did some changes to move out geos things into geos.c / pygeom.c in the coordinates PR, and included that here as well to see if all is working.

One thing that I ran into is that the ufunc registry functions don't copy the passed arguments, and you need to ensure that all those objects are kept alive as long as the ufunc objects exist. That caused segfaults when calling `init_ufuncs` defined in `ufuncs.c` from `lib.c` (as all those arguments where not declared in ufuncs.h, only the init function, I suppose). For now I "fixed" this by just having a ufuncs.h and including that fully instead of a ufuncs.c + ufuncs.h.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@mattip or @seberg do you have any experience with this? What I am trying to do is to register ufuncs defined in one .c file (`ufuncs.c`) to add them to the C extension module and register them with numpy in another .c file (`lib.c`). Should that be possible? (getting segfaults right now) 
Main reason I am trying to do that is for better code organisation / smaller files.

**Comment by seberg** [comment]
Hmmm, I do not see why that should not work, but probably I am missing some linking issue. How does it segfault? The way the ufunc API works is by populating a struct with function pointers.

**Comment by jorisvandenbossche** [comment]
It segfaults on import.

**Comment by jorisvandenbossche** [comment]
(small note: what is in the diff here works. It's only when I have `ufuncs.c` with all data and functions and `ufuncs.h` with just the `init_ufuncs` declaration to include in `lib.c` that it segfaults)

**Comment by jorisvandenbossche** [comment]
@seberg Ah, found it. I also need to guard for the ufunc API (`#define NO_IMPORT_UFUNC`, in addition to `NO_IMPORT_ARRAY`)

**Comment by jorisvandenbossche** [comment]
@caspervdw since you said elsewhere you were OK with the rename of `ufuncs` to `lib`, I am going to merge this, so I can fix the merge conflicts with your coords PR

The main difference is the return of 0 or 1. For now, I left it as is (so not changing to return 1 as you did it in your PR), as this seems to be how all numpy examples do it. But we can of course still discuss / change in a separate PR.

**Comment by caspervdw** [comment]
Thanks @jorisvandenbossche  for pushing this. 

If you are talking about the change in the return value of `init_geos` or `init_geom_type`; I think I changed that to 0 (error) or 1 (OK) indeed. That lead to slightly nicer syntax. But if numpy does it like -1 (error), 0 (OK), then apparently that is customary so :+1: on keeping it. It does matches exit codes now I think about it.

**Comment by jorisvandenbossche** [comment]
>  It does matches exit codes now I think about it.

I indeed matches that, but then is inconsistent with all other functions that return 0 / NULL on exception ..
But so the rule is then for the `init_` functions we follow the exit-code style, for all other things we follow the more natural 0 on exception style.

**Pull request merged**
